TebexConfiguration:
  TebexSecret: "" # Here goes your tebex secret key
  TebexCheckInterval: 60 # Seconds
  TebexUrl: "https://plugin.tebex.io/"
  StoreURL: "yourstore.com"
  StoreCommand: "/donate" # The command a player will execute to go to the store